Add generic rolling window function
fastats/fastats pull request #22
Opened 2017-11-12 21:18 UTC by dwillmer

- `windowed_pass` - API / function name is subject to change, all recommendations welcome.

2017-11-12 21:19 UTC, dwillmer commented
Should be merged after #20 and #21, built on the same commits

2017-11-13 22:20 UTC, dwillmer commented
Added a rolling ols example + unit-tests.

Needs a wrapping function to work due to the multiple args, but that actually works out as an advantage when it comes to t-stats/r^2.

Unfortunately this raised an issue with raw numpy functions being used in the ols functions - we need to call them as module-level functions to ensure they don't get re-parsed. Ufuncs / c-api / cython functions will just error when re-parsed

2017-11-15 22:04 UTC, dwillmer commented
Added an example to show multiple return values from a function - t-stats and r^2 in a rolling OLS.

2017-11-15 23:45 UTC, pawroman commented
Current PR makes it hard to review due to changes pulled in from other branch

2017-11-19 23:28 UTC, dwillmer commented
Yea, agreed, let's merge the others first.

2017-12-13 14:19 UTC, pawroman commented
Need to resolve conflicts and should be good to review.

2017-12-13 20:47 UTC, dwillmer commented
@fastats/core  - conflicts resolved, please review.

2017-12-13 21:28 UTC, pawroman requested changes
Looks good, just one `pytest.main()` call to fix. Also, I'm wondering how it's passing the coverage checks.

2017-12-13 21:28 UTC, pawroman commented on fastats/core/windowed_pass.py
> +    pytest.main()
`pytest.main([__file__])`

2017-12-13 21:31 UTC, pawroman commented on tests/core/test_windowed_pass.py
> +    raw = windowed_pass(data, 5)
Is this how you make coverage work?

2017-12-13 22:16 UTC, dwillmer commented on tests/core/test_windowed_pass.py
> +    raw = windowed_pass(data, 5)
yea, call it without substitutions

2017-12-13 22:19 UTC, dwillmer commented on fastats/core/windowed_pass.py
> +    pytest.main()
Thanks, fixed!

2017-12-13 22:21 UTC, pawroman approved these changes

2017-12-13 22:25 UTC, merged